# Generated by Django 3.1.6 on 2021-02-26 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_tweet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
