# Generated by Django 3.1.6 on 2021-02-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_auto_20210224_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='post_id',
        ),
        migrations.AddField(
            model_name='tweet',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
