# Generated by Django 3.1.6 on 2021-02-26 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_auto_20210224_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_text',
            field=models.TextField(max_length=280),
        ),
    ]
